#!/bin/bash -e

REPORT=/tmp/report.txt

ping -n -c 3 $TARGET_IP

cp /scans/monitor.pcap monitor.pcap

python network_tests.py connection.dhcp_long monitor.pcap $TARGET_IP

cat report.txt >> $REPORT

#To understand how to adjust DAQ DHCP leasetime the following docs are useful
#daq/misc/increase_leasetime
#daq/testing/test_many.sh
#daq/misc/runtime_configs/long_wait/port-01/ping_runtime.sh
#system.conf >> parameter >> monitor_scan_sec=5