#!/bin/bash -e

$REPORT=/tmp/report.txt

$SECONDS = 300

ping -n -c 3 $TARGET_IP

python network_min_capture.py $SECONDS

python network_tests.py connection.min_send capture.pcap $TARGET_IP

mkdir /tmp

mv report.txt $REPORT

cat $REPORT
