#!/bin/bash -e

REPORT=/tmp/report.txt

ping -n -c 3 $TARGET_IP

cp /scans/monitor.pcap capture.pcap

python network_tests.py network.ntp.update capture.pcap $TARGET_IP

mv report.txt $REPORT

cat $REPORT