#!/bin/bash -e

REPORT=/tmp/report.txt

MONITOR=/scans/monitor.pcap

python network_tests.py connection.dhcp_long $MONITOR $TARGET_IP
python network_tests.py network.ntp.update $MONITOR $TARGET_IP
python network_tests.py protocol.app_min_send $MONITOR $TARGET_IP
python network_tests.py connection.min_send $MONITOR $TARGET_IP
python network_tests.py communication.type $MONITOR $TARGET_IP
python network_tests.py security.network.802_1x $MONITOR $TARGET_IP

cat report.txt >> $REPORT