#!/bin/bash -e

REPORT=/tmp/report.txt

FIVE_MINS = 300

ping -n -c 3 $TARGET_IP

python network_min_capture.py $FIVE_MINS

sleep $FIVE_MINS

python network_tests.py network.min_send capture.pcap $TARGET_IP

mv report.txt $REPORT

cat $REPORT
