FROM daq/aardvark:latest as bacnet_build

# Do this alone first so it can be re-used by other build files.
RUN $AG update && $AG install openjdk-8-jre

RUN $AG update && $AG install openjdk-8-jdk git

#This refer to a specific github commit on the repo
ENV BACHASH=05ed3fa7e574a6f4fb86ffadb037c60ead08a871

RUN bin/retry_cmd git clone https://github.com/JoelRedstone/bacnet4j.git --single-branch \
  && cd bacnet4j && git reset --hard $BACHASH && ../bin/retry_cmd ./gradlew shadow

FROM daq/aardvark:latest

RUN $AG update && $AG install openjdk-8-jre

COPY --from=bacnet_build /root/bacnet4j/*.jar bacnet4j/

COPY subset/bacnet/versiontest/test_version .

CMD ["./test_version"]
