sudo: required
dist: bionic
services:
  - docker
jdk:
  - openjdk9
addons:
  apt:
    update: true
    packages:
      - openvswitch-switch
install:
  - set -e
  - bin/setup_daq
script:
  - set -e
  - bin/test_daq
env:
  global:
    - DOCKER_STARTUP_TIMEOUT_MS=60000
    - DAQ_FAUCET_REPO=https://github.com/grafnu/faucet
    - DAQ_FAUCET_VER=bc1ba033318c8d66070fc7b215216445c135a4b3
  matrix:
    #- DAQ_TEST=base
    #- DAQ_TEST=many
    #- DAQ_TEST=aux
    #- DAQ_TEST=topo
    - DAQ_TEST=stack
branches:
  except:
  - /^release-\d+\.\d+(\.\d+)?$/
