sudo: required
dist: trusty
language: python
python:
  - "3.6"
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - openvswitch-switch
install:
  - set -e
  - bin/setup_base
  - bin/setup_dev
script:
  - set -e
  - bin/build_daq
  - bin/test_daq
env:
  global:
    - DOCKER_STARTUP_TIMEOUT_MS=60000
  matrix:
    - DAQ_MODE=in DAQ_BUILD=in
    - DAQ_MODE=in DAQ_BUILD=no
    - DAQ_CONF=misc/faucet_multi.yaml DAQ_MUD=true DAQ_RUNS=10
    - DAQ_CODECOV=y DAQ_VERIFY=inst/run-port-01/nodes/nmap01/return_code.txt
    - DAQ_FAIL=telnet DAQ_VERIFY=inst/run-port-01/nodes/pass01/return_code.txt
    - DAQ_FAIL=!telnet DAQ_MUD=true DAQ_VERIFY=inst/run-port-01/nodes/pass01/return_code.txt
    - DAQ_CONF=misc/faucet_multi.yaml DAQ_VERIFY=inst/run-port-03/nodes/nmap03/return_code.txt
    - DAQ_CONF=misc/faucet_ext.yaml DAQ_VERIFY=inst/run-port-02/nodes/nmap02/return_code.txt
branches:
  except:
  - /^release-\d+\.\d+(\.\d+)?$/
