sudo: required
dist: trusty
language: python
python:
  - "3.6"
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - openvswitch-switch
install:
  - set -e
  - bin/setup_daq
script:
  - set -e
  - bin/test_daq
env:
  global:
    - DOCKER_STARTUP_TIMEOUT_MS=60000
  matrix:
    - DAQ_TEST=base
    - DAQ_TEST=many
    - DAQ_TEST=aux
    - DAQ_TEST=topo
    - DAQ_TEST=stack DAQ_FAUCET_REPO=https://github.com/anarkiwi/faucet DAQ_FAUCET_BRANCH=stackingredundancy-test
branches:
  except:
  - /^release-\d+\.\d+(\.\d+)?$/
