sudo: required
dist: bionic
services:
  - docker
jdk:
  - openjdk8
addons:
  apt:
    update: true
    packages:
      - openvswitch-switch
install:
  - set -e
  - bin/setup_daq
script:
  - set -e
  - bin/test_daq
env:
  global:
    - DOCKER_STARTUP_TIMEOUT_MS=60000
  matrix:
    - DAQ_TEST=base
    - DAQ_TEST=many
    - DAQ_TEST=aux
    - DAQ_TEST=topo
    - DAQ_TEST=stack DAQ_FAUCET_REPO=https://github.com/grafnu/faucet DAQ_FAUCET_VER=28c3c66d95ccddad6d6da99f3995dbc7d931bede
branches:
  except:
  - /^release-\d+\.\d+(\.\d+)?$/
