# Image name: daq/faux
#
# Faux device for framework development/testing.
#

FROM daq/aardvark:latest

# Do this alone first so it can be re-used by other build files.
RUN $AG update && $AG install openjdk-8-jre

RUN $AG update && $AG install openjdk-8-jdk git

RUN $AG update && $AG install jq

COPY validator/ validator/
RUN validator/bin/build

COPY schemas/udmi/ schemas/udmi/

COPY subset/cloud/test_udmi .

CMD ./test_udmi
