# Image name: daq/faux
#
# Faux device for framework development/testing.
#

FROM daq/aardvark:latest

# Run this separately so it can be shared with other builds.
RUN $AG update && $AG install openjdk-8-jre

RUN $AG update && $AG install openjdk-8-jdk git

COPY validator/ validator/
RUN validator/bin/build

ENTRYPOINT ["bin/validate"]
