#!/bin/bash -e

REPORT=/tmp/report.txt

# Necessary to reach gcp. Should be done by framework but this works for now.
route add default gw $GATEWAY_IP

gcp_cred=/config/inst/gcp_service_account.json
gcp_topic=target
schema_path=schemas/udmi

if [ ! -f $gcp_cred ]; then
    echo Missing $gcp_cred file, skipping udmi validation. | tee -a $REPORT
    echo RESULT skip cloud.udmi.pointset | tee -a $REPORT
    exit 0
fi

device_id=`jq .device_id /config/device/module_config.json`

export GOOGLE_APPLICATION_CREDENTIALS=$gcp_cred
echo Using credentials from $GOOGLE_APPLICATION_CREDENTIALS
echo Configured topic is $gcp_topic
echo Configured schema is $schema_path
echo Target device is $device_id
echo

timeout 60 validator/bin/validate $PWD/$schema_path pubsub:$gcp_topic $HOSTNAME

base=schemas/udmi/out/pointset_$device_id

ls -l $base.*

if [ -f "$base.out" ]; then
    result=fail
    detail=`head -n 1 $base.out`
elif [ -f "$base.json" ]; then
    result=pass
else
    result=fail
    detail="No result found"
fi

echo RESULT $result cloud.udmi.pointset $detail | tee -a $REPORT
