#!/bin/bash -e

gcp_cred=local/google_credentials.json
gcp_topic=target
schema_path=schemas/udmi

export GOOGLE_APPLICATION_CREDENTIALS=$PWD/$gcp_cred
echo Using credentials from $GOOGLE_APPLICATION_CREDENTIALS
echo Configured topic is $gcp_topic
echo Configured schema is $schema_path
echo

validator/bin/validate $PWD/$schema_path pubsub:$gcp_topic $gcp_ignoreset
