#!/bin/bash -e

REPORT=/tmp/report.txt
VLOG=/tmp/validaton.log

# Necessary to reach gcp. Should be done by framework but this works for now.
route add default gw $GATEWAY_IP

gcp_cred=/config/inst/google_credentials.json
gcp_topic=target
schema_path=schemas/udmi

if [ ! -f $gcp_cred ]; then
    echo Missing $gcp_cred file, skipping udmi validation. | tee -a $REPORT
    echo RESULT skip cloud.udmi.pointset | tee -a $REPORT
    exit 0
fi

export GOOGLE_APPLICATION_CREDENTIALS=$gcp_cred
echo Using credentials from $GOOGLE_APPLICATION_CREDENTIALS
echo Configured topic is $gcp_topic
echo Configured schema is $schema_path
echo

result=fail
timeout 60 validator/bin/validate $PWD/$schema_path pubsub:$gcp_topic $gcp_ignoreset | tee -a $VLOG

more schemas/udmi/out/* | tee -a $VLOG

echo RESULT $result cloud.udmi.pontset | tee -a $REPORT
