FROM daq/aardvark:latest

RUN $AG update && $AG install openjdk-8-jre

RUN $AG update && $AG install openjdk-8-jdk git

COPY subset/password/ .

RUN cd brute_test && ./gradlew build 

CMD ["./test_password"]
