#!/bin/bash -e 

if [ -n "$TARGET_IP" ]; then 
	echo Using the host address from $TARGET_IP.
	java -jar brute_test/build/libs/brute_test.jar $TARGET_IP ssh 22
	cat ./tmp/sshReport.txt >> /tmp/report.txt

	java -jar brute_test/build/libs/brute_test.jar $TARGET_IP telnet 23
	cat ./tmp/telnetReport.txt >> /tmp/report.txt

	cp -r tmp/report.txt /tmp/report.txt
else 	
	echo Wrong parametres Brute test failed | tee /tmp/report.txt
fi 



