FROM daq/aardvark:latest

# Do this alone first so it can be re-used by other build files.
RUN $AG update && $AG install openjdk-8-jre

RUN $AG update && $AG install openjdk-8-jdk git

RUN $AG update && $AG install maven tcpdump jq

COPY subset/switches/ switches/
COPY subset/switches/module_manifest.json .
COPY utils/reporting.sh .

RUN cd switches && mvn clean compile assembly:single

CMD ["./switches/test_switch"]
