#!/bin/bash -e
source reporting_utils
REPORT=/tmp/report.txt

# Setup for accessing control plane switch. If LOCAL_IP is defined, which
# is the intended local address for this node on the control plane then
# SWITCH_IP will be the IP address of the OpenFlow switch.
if [ -n "$LOCAL_IP" ]; then
    echo Configuring network with local address $LOCAL_IP.
    ip addr add $LOCAL_IP dev `hostname`-eth0
    echo Switch test with port $SWITCH_PORT.
    ping -n -c 10 $SWITCH_IP
    POE_ENABLED=`jq -r .modules.switch.poe.enabled /config/device/module_config.json`
    java -jar switches/target/switchtest-0.0.1-jar-with-dependencies.jar $SWITCH_IP $SWITCH_PORT $POE_ENABLED
    cp -r tmp/report.txt /tmp/report.txt
else

    SKIP_REASON="LOCAL_IP not configured, assuming no network switch."
    RESULT="skip"
    SUMMARY="No local IP"

    write_out_result $REPORT \
                     "connection.port_link" \
                     "description" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT connection.port_link $SUMMARY"

    write_out_result $REPORT \
                     "connection.port_speed" \
                     "description" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT connection.port_speed $SUMMARY"

    write_out_result $REPORT \
                     "connection.port_duplex" \
                     "description" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT connection.port_duplex $SUMMARY"

    write_out_result $REPORT \
                     "poe.power" \
                     "description" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT poe.power $SUMMARY"

    write_out_result $REPORT \
                     "poe.negotiation" \
                     "description" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT poe.negotiation $SUMMARY"

    write_out_result $REPORT \
                     "poe.support" \
                     "description" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT poe.support $SUMMARY"

fi
