#!/bin/bash -e

local=n

if [ "$1" == local ]; then
    local=y
    shift
fi

if [ -z "$1" ]; then
    FDIR=inst/
else
    FDIR=inst/faucet/daq-faucet-$1/
    shift
fi

echo Using instance dir $FDIR, local=$local

local_version=$(cd forch; git rev-list -n 1 HEAD)
target_version=$(cat misc/FORCH_VERSION)
target_commit=$(cd forch; git rev-parse $target_version)
if [ $local == n -a "$target_commit" != "$local_version" ]; then
    echo Local forch commit is at: $local_version
    echo Mismatch with misc/FORCH_VERSION: $target_version
    echo Try 'bin/clean_dev && bin/setup_dev' to reset.
    false
fi


FAUCET_EVENT_SOCK=$(realpath $FDIR)/faucet_event.sock \
    FORCH_CONFIG_DIR=$(realpath $FDIR) \
    forch/bin/forch $*
