#!/bin/bash -e

FSOCK=faucet_event.sock

if [ -z "$1" ]; then
    FDIR=inst/
else
    FDIR=inst/faucet/daq-faucet-$1/
fi

echo Using instance dir $FDIR

if [ -f venv/bin/python ]; then
    PYTHON=venv/bin/python
else
    PYTHON=python3
fi

sudo \
    FAUCET_EVENT_SOCK=$FDIR/$FSOCK FORCH_CONFIG_DIR=$FDIR FORCH_RUN_DIR=$FDIR \
    $PYTHON daq/forchestrator.py
