#!/bin/bash -e

if [ -z "$1" ]; then
    SOCK=inst/faucet_event.sock
    CPN_FILE=inst/cpn.yaml
else
    SOCK=inst/faucet/daq-faucet-$1/faucet_event.sock
    CPN_FILE=inst/faucet/daq-faucet-$1/cpn.yaml
fi

echo Using event socket $SOCK
echo Using CPN config file $CPN_FILE

sudo FAUCET_EVENT_SOCK=$SOCK CPN_CONFIG_FILE=$CPN_FILE venv/bin/python daq/forchestrator.py
