FROM daq/aardvark:latest

RUN $AG update && $AG install openjdk-8-jre

RUN $AG update && $AG install openjdk-8-jdk

RUN $AG update && $AG install maven 

COPY subset/alliedSwitch/ .
COPY subset/test_switch .

CMD ./test_switch
