FROM daq/aardvark:latest

RUN $AG update && $AG install openjdk-8-jre

RUN $AG update && $AG install openjdk-8-jdk git

RUN $AG update && $AG install curl 

COPY subset/security/ .

RUN curl https://svn.nmap.org/nmap/nmap-mac-prefixes | tee brute_test/src/main/resources/macList.txt

RUN cd brute_test && ./gradlew shadowJar 

CMD ["./test_password"]
