#!/bin/bash -e

if [ -n "$TARGET_IP" ]; then
	echo Using the host address from $TARGET_IP and mac address $TARGET_MAC

        curl https://svn.nmap.org/nmap/nmap-mac-prefixes | tee brute_test/src/main/resources/macList.txt
	java -jar brute_test/build/libs/brute_test-all.jar $TARGET_IP ssh 22 $TARGET_MAC
	cat ./reports/sshReport.txt >> ./reports/report.txt

        java -jar brute_test/build/libs/brute_test-all.jar $TARGET_IP telnet 23 $TARGET_MAC
	cat ./reports/telnetReport.txt >> ./reports/report.txt
	cp -r ./reports/report.txt /tmp/report.txt
else
	echo Wrong parametres Password test failed | tee /tmp/report.txt
fi
