#!/bin/bash -e

if [ -n "$TARGET_IP" ]; then
	echo Using the host address from $TARGET_IP and mac address $TARGET_MAC

	java -jar brute_test/build/libs/brute_test-all.jar $TARGET_IP 22 $TARGET_MAC
	cat ./reports/sshReport.txt >> ./reports/report.txt
	cp -r ./reports/report.txt /tmp/report.txt
else
	echo Wrong parameters Password test failed | tee /tmp/report.txt
fi
